openapi: 3.0.3
info:
  title: exo5 openapi
  version: 1.0.0
servers:
  - url: 'http://localhost:8000'
tags:
  - name: Orders
  - name: Products
paths:
  /orders:
    get:
      tags:
        - Orders
      parameters:
        - $ref: '#/components/parameters/PageQueryParameter'
        - $ref: '#/components/parameters/PageSizeQueryParameter'
      responses:
        200:
          description: List of orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
    post:
      tags:
        - Orders
      security:
        - basicAuth: [ ]
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Order'
      responses:
        200:
          description: Orders created
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
  /products:
    get:
      tags:
        - Products
      parameters:
        - $ref: '#/components/parameters/LimitQueryParameter'
        - $ref: '#/components/parameters/SearchQueryParameter'
      responses:
        200:
          description: Products filtered
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
              examples:
                multipleProducts:
                  summary: Multiple products
                  value:
                    - name: Lait
                      expiration_datetime: 2025-09-01T00:00:00.004Z
                      price: 5000.0
                noProducts:
                  summary: Result with any product
                  value: [ ]
components:
  parameters:
    PageQueryParameter:
      in: query
      name: page
      schema:
        type: integer
    PageSizeQueryParameter:
      in: query
      name: size
      schema:
        type: integer
    LimitQueryParameter:
      in: query
      name: limit
      schema:
        type: integer
      required: false
    SearchQueryParameter:
      in: query
      name: q
      schema:
        type: string
      required: false
  schemas:
    Order:
      type: object
      properties:
        identifier:
          type: integer
        customer_name:
          type: string
        creation_dateitme:
          type: string
          format: date-time
        total_amount:
          type: number
          format: float
    Product:
      type: object
      properties:
        name:
          type: string
        expiration_datetime:
          type: string
          format: date-time
        price:
          type: number
          format: float
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic